# Generated by Django 4.0.4 on 2022-05-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='category',
            field=models.ManyToManyField(null=True, to='page.category'),
        ),
    ]
