# Generated by Django 4.0.4 on 2022-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercustom_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='location',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='activeuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='phone_father',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
