# Generated by Django 4.0.4 on 2022-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('accounts', '0003_remove_usercustom_bio_remove_usercustom_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='category',
            field=models.ManyToManyField(blank=True, to='page.category'),
        ),
    ]
