# Generated by Django 4.0.4 on 2022-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_categoryblog_chekout_commentblog_contactmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='deatil',
            field=models.TextField(max_length=200),
        ),
    ]
