# Generated by Django 4.0.4 on 2022-06-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_postblog_deatil'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Answer', 'Answer')], default='Pending', max_length=50),
        ),
    ]
