# Generated by Django 4.0.4 on 2022-06-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_postblog_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeWork',
        ),
    ]
