# Generated by Django 4.0.4 on 2022-07-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_postblog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryblog',
            name='amount',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
